use std::path::PathBuf;

fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").unwrap() == "windows" {
        println!("cargo:rustc-link-search=native=.");
        println!("cargo:rustc-link-lib=static=rtlsdr");
    }

    // Compile all exported Slint components used by the app and standalone applets.
    //
    // Slint generates one Rust file per `.slint` compile invocation in OUT_DIR.
    // We then stitch them together into a single include file so every crate
    // target (lib/bin/examples/tests) gets the same set of exported types.
    slint_build::compile("ui/app.slint").expect("Slint build failed");
    slint_build::compile("ui/applets/auto_waveshaping.slint").expect("Slint build failed");
    slint_build::compile("ui/applets/spectral_ingester.slint").expect("Slint build failed");
    slint_build::compile("ui/applets/ps5_deck.slint").expect("Slint build failed");
    slint_build::compile("ui/applets/joycon_wand.slint").expect("Slint build failed");
    slint_build::compile("ui/applets/toto_hud.slint").expect("Slint build failed");
    slint_build::compile("ui/applets/mamba_brain.slint").expect("Slint build failed");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR missing"));
    let stitched = out_dir.join("slint_all.rs");

    // Keep this list in sync with the slint_build::compile() calls above.
    let stitched_src = r#"// Auto-generated by build.rs.
// This file includes all Slint-generated Rust bindings for the package.

include!(concat!(env!(\"OUT_DIR\"), \"/app.rs\"));
include!(concat!(env!(\"OUT_DIR\"), \"/auto_waveshaping.rs\"));
include!(concat!(env!(\"OUT_DIR\"), \"/spectral_ingester.rs\"));
include!(concat!(env!(\"OUT_DIR\"), \"/ps5_deck.rs\"));
include!(concat!(env!(\"OUT_DIR\"), \"/joycon_wand.rs\"));
include!(concat!(env!(\"OUT_DIR\"), \"/toto_hud.rs\"));
include!(concat!(env!(\"OUT_DIR\"), \"/mamba_brain.rs\"));
"#;

    std::fs::write(&stitched, stitched_src).expect("write slint_all.rs");
    println!("cargo:rustc-env=SLINT_INCLUDE_GENERATED={}", stitched.display());
}
