[target.x86_64-pc-windows-msvc]
# Increase default stack size to avoid running out of stack
# space in debug builds. The size matches Linux's default.
rustflags = ["-C", "link-arg=/STACK:8000000"]
linker = "rust-lld.exe"

[target.aarch64-pc-windows-msvc]
# Increase default stack size to avoid running out of stack
# space in debug builds. The size matches Linux's default.
rustflags = ["-C", "link-arg=/STACK:8000000"]

# for Linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# for RP2350 (commented out - use x86_64-pc-windows-msvc for main builds)
# [build]
# target = "thumbv6m-none-eabi"

# [target.thumbv6m-none-eabi]
# runner = "probe-rs run --chip RP2350"
