//! GPU-Driven Dispatch Kernel
//!
//! Autonomously processes audio through rolling v-buffer history.
//! GPU generates work items for CPU (not vice versa).
//!
//! # Architecture
//!
//! Rolling V-Buffer (Unified Memory):
//! - GPU writes every frame: vbuffer.data[write_head % CAPACITY]
//! - CPU reads any frame: vbuffer.data[frame_idx] (entire history accessible)
//! - No PCIe copies, no synchronization overhead - same address space for both
//!
//! # Example
//!
//! ```no_run
//! use twister::dispatch_kernel::{AutonomousDispatchKernel, AudioFrameVBuffer};
//!
//! let device = todo!("Get wgpu device");
//! let queue = device.queue();
//! let mut kernel = AutonomousDispatchKernel::new(device, queue).unwrap();
//!
//! // CPU feeds audio frames into v-buffer
//! let frames = vec![AudioFrameVBuffer::default(); 32];
//! kernel.enqueue_audio_frames(&frames).unwrap();
//!
//! // GPU autonomously processes
//! kernel.dispatch_autonomous_batch();
//!
//! // CPU dequeues work generated by GPU
//! let processed = kernel.dequeue_processed_frames();
//! let results = kernel.read_results();
//! ```

use crate::gpu_memory::{GpuWorkQueue, UnifiedBuffer};
use bytemuck::{Pod, Zeroable};
use std::sync::atomic::{AtomicU32, Ordering};
use wgpu::{ComputePipeline, Device, Queue};

/// Audio frame structure (compatible with v-buffer).
///
/// Represents a single audio frame from all 4 channels with timing information.
/// Aligned to 32 bytes for GPU memory efficiency.
#[repr(C)]
#[derive(Copy, Clone, Pod, Zeroable)]
pub struct AudioFrameVBuffer {
    /// Front-left channel sample
    pub sample_fl: f32,
    /// Front-right channel sample
    pub sample_fr: f32,
    /// Rear-left channel sample
    pub sample_rl: f32,
    /// Rear-right channel sample
    pub sample_rr: f32,
    /// Microsecond timestamp
    pub timestamp_us: u64,
    /// Index in rolling buffer
    pub frame_index: u32,
    /// Padding for alignment
    pub _padding: [u32; 1],
}

impl Default for AudioFrameVBuffer {
    fn default() -> Self {
        Self {
            sample_fl: 0.0,
            sample_fr: 0.0,
            sample_rl: 0.0,
            sample_rr: 0.0,
            timestamp_us: 0,
            frame_index: 0,
            _padding: [0; 1],
        }
    }
}

/// Dispatch result written to unified v-buffer.
///
/// Contains detection and localization results from autonomous GPU processing.
/// Aligned to 32 bytes for GPU memory efficiency.
#[repr(C)]
#[derive(Copy, Clone, Pod, Zeroable)]
pub struct DispatchResultVBuffer {
    /// Detected frequency in Hz
    pub detected_frequency_hz: f32,
    /// Anomaly score in dB
    pub anomaly_score_db: f32,
    /// Beamform azimuth in degrees
    pub beamform_azimuth_degrees: f32,
    /// Beamform elevation in degrees
    pub beamform_elevation_degrees: f32,
    /// RF power in dBFS
    pub rf_power_dbfs: f32,
    /// Detection confidence [0, 1]
    pub confidence: f32,
    /// Padding for alignment
    pub _padding: [u32; 2],
}

impl Default for DispatchResultVBuffer {
    fn default() -> Self {
        Self {
            detected_frequency_hz: 0.0,
            anomaly_score_db: 0.0,
            beamform_azimuth_degrees: 0.0,
            beamform_elevation_degrees: 0.0,
            rf_power_dbfs: 0.0,
            confidence: 0.0,
            _padding: [0; 2],
        }
    }
}

/// Configuration for autonomous dispatch kernel.
#[derive(Clone, Debug)]
pub struct DispatchKernelConfig {
    /// V-buffer capacity (number of audio frames)
    pub vbuffer_capacity: usize,
    /// Number of frames per dispatch batch
    pub batch_size: u32,
    /// Detection threshold (dB)
    pub detection_threshold_db: f32,
    /// Beamforming azimuth resolution (degrees)
    pub azimuth_resolution: f32,
}

impl Default for DispatchKernelConfig {
    fn default() -> Self {
        // Capacity: 192kHz * 0.1s = 19,200 frames
        // Batch size: 32 frames (typical GPU workgroup)
        Self {
            vbuffer_capacity: 19_200,
            batch_size: 32,
            detection_threshold_db: -40.0,
            azimuth_resolution: 5.0,
        }
    }
}

/// Autonomous dispatch kernel manager.
///
/// Manages GPU-driven dispatch processing with zero-copy v-buffer integration.
/// GPU writes results directly to unified memory; CPU reads without copying.
pub struct AutonomousDispatchKernel {
    device: Device,
    queue: Queue,

    /// V-buffer for audio input (rolling history)
    audio_vbuffer: UnifiedBuffer<AudioFrameVBuffer>,

    /// V-buffer for dispatch results (rolling history)
    results_vbuffer: UnifiedBuffer<DispatchResultVBuffer>,

    /// Work queue: GPU enqueues indices, CPU dequeues
    work_queue: GpuWorkQueue<u32>,

    /// GPU compute pipeline
    compute_pipeline: ComputePipeline,

    /// Bind group for shader access
    bind_group: wgpu::BindGroup,

    /// Frame counter (for rolling buffer positioning)
    frame_counter: AtomicU32,

    /// Configuration
    config: DispatchKernelConfig,
}

impl AutonomousDispatchKernel {
    /// Create a new autonomous dispatch kernel.
    ///
    /// # Parameters
    /// - `device`: wgpu Device for GPU buffer allocation
    /// - `queue`: wgpu Queue for GPU command submission
    /// - `config`: Optional configuration (defaults to Config::default())
    ///
    /// # Returns
    /// Result<Self, Box<dyn std::error::Error>>
    ///
    /// # Errors
    /// Returns error if shader compilation fails or buffers cannot be allocated
    pub fn new(
        device: Device,
        queue: Queue,
        config: Option<DispatchKernelConfig>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let config = config.unwrap_or_default();

        // Create rolling v-buffers (unified memory)
        let audio_vbuffer = UnifiedBuffer::new(&device, config.vbuffer_capacity);
        let results_vbuffer = UnifiedBuffer::new(&device, config.vbuffer_capacity);
        let work_queue = GpuWorkQueue::new();

        // Load and compile compute shader
        let shader_source = include_str!("../shaders/dispatch_kernel.wgsl");
        let shader_module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("dispatch_kernel"),
            source: wgpu::ShaderSource::Wgsl(std::borrow::Cow::Borrowed(shader_source)),
        });

        // Create pipeline layout
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("dispatch_kernel_layout"),
            bind_group_layouts: &[],
            immediate_size: 0,
        });

        // Create compute pipeline
        let compute_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("dispatch_kernel_pipeline"),
            layout: Some(&pipeline_layout),
            module: &shader_module,
            entry_point: Some("autonomous_dispatch"),
            compilation_options: Default::default(),
            cache: None,
        });

        // Create bind group with buffer bindings
        let bind_group =
            Self::create_bind_group(&device, &pipeline_layout, &audio_vbuffer, &results_vbuffer)?;

        Ok(Self {
            device,
            queue,
            audio_vbuffer,
            results_vbuffer,
            work_queue,
            compute_pipeline,
            bind_group,
            frame_counter: AtomicU32::new(0),
            config,
        })
    }

    /// CPU feeds audio frames into v-buffer.
    ///
    /// GPU will autonomously process frames from the v-buffer.
    /// This is a zero-copy operation: frames are written directly to GPU memory.
    ///
    /// # Parameters
    /// - `frames`: Slice of audio frames to enqueue
    ///
    /// # Returns
    /// Result<(), Box<dyn std::error::Error>>
    ///
    /// # Errors
    /// Returns error if write exceeds v-buffer capacity
    pub fn enqueue_audio_frames(
        &mut self,
        frames: &[AudioFrameVBuffer],
    ) -> Result<(), Box<dyn std::error::Error>> {
        if frames.is_empty() {
            return Ok(());
        }

        let write_head = self
            .frame_counter
            .fetch_add(frames.len() as u32, Ordering::SeqCst);

        // Write frames to rolling v-buffer (unified memory, no PCIe copy)
        let write_offset = (write_head as usize) % self.config.vbuffer_capacity;
        self.audio_vbuffer
            .gpu_write(&self.queue, frames, write_offset)?;

        Ok(())
    }

    /// Dispatch autonomous GPU kernel.
    ///
    /// GPU processes frames from v-buffer and generates work items for CPU.
    /// Non-blocking call: GPU executes asynchronously.
    ///
    /// # Behavior
    /// - Creates compute pass with workgroups
    /// - Each workgroup processes one batch of frames
    /// - GPU writes results to results_vbuffer
    /// - GPU enqueues frame indices to work_queue
    pub fn dispatch_autonomous_batch(&self) {
        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("dispatch_kernel_encoder"),
            });

        {
            let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("dispatch_kernel_pass"),
                timestamp_writes: None,
            });
            cpass.set_pipeline(&self.compute_pipeline);
            cpass.set_bind_group(0, &self.bind_group, &[]);

            // Workgroups: (32 threads) × (32 batches) = 1024 parallel frame processing
            cpass.dispatch_workgroups(self.config.batch_size, 1, 1);
        }

        self.queue.submit(std::iter::once(encoder.finish()));
    }

    /// CPU dequeues work generated by GPU.
    ///
    /// Returns frame indices that were processed by the GPU.
    /// Non-blocking: returns empty vec if no work available.
    ///
    /// # Returns
    /// Vec<u32> of processed frame indices
    pub fn dequeue_processed_frames(&self) -> Vec<u32> {
        let mut frames = Vec::new();

        while self.work_queue.has_pending() {
            let frame_idx = self.work_queue.cpu_dequeue();
            frames.push(frame_idx);
        }

        frames
    }

    /// Get results from unified v-buffer (zero-copy).
    ///
    /// Returns slice of all dispatch results. GPU and CPU share same memory.
    /// Latency: < 1 microsecond (unified memory, no copies)
    ///
    /// # Returns
    /// Slice of DispatchResultVBuffer containing all results
    pub fn read_results(&self) -> &[DispatchResultVBuffer] {
        self.results_vbuffer.cpu_read()
    }

    /// Acknowledge results have been read by CPU.
    ///
    /// Signals to v-buffer that CPU is done reading, allowing GPU to overwrite.
    /// Must be called after read_results() before next dispatch.
    pub fn ack_results_read(&self) {
        self.results_vbuffer.cpu_ack_read();
    }

    /// Get current frame counter value.
    ///
    /// # Returns
    /// Number of frames enqueued since kernel creation
    pub fn frame_count(&self) -> u32 {
        self.frame_counter.load(Ordering::Acquire)
    }

    /// Get current configuration.
    ///
    /// # Returns
    /// Reference to kernel configuration
    pub fn config(&self) -> &DispatchKernelConfig {
        &self.config
    }

    /// Create bind group with buffer bindings.
    ///
    /// Internal helper for GPU resource management.
    fn create_bind_group(
        device: &Device,
        _layout: &wgpu::PipelineLayout,
        audio_vbuffer: &UnifiedBuffer<AudioFrameVBuffer>,
        results_vbuffer: &UnifiedBuffer<DispatchResultVBuffer>,
    ) -> Result<wgpu::BindGroup, Box<dyn std::error::Error>> {
        // Note: This is a placeholder implementation.
        // In a full implementation, this would:
        // - Create bind group layout with proper resource bindings
        // - Bind audio_vbuffer.gpu_buffer (read)
        // - Bind results_vbuffer.gpu_buffer (read_write)
        // - Bind work_queue buffer (atomic operations)
        // - Return configured BindGroup

        // For now, we create a minimal bind group
        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("dispatch_kernel_bgl"),
            entries: &[
                // Audio v-buffer (storage, read)
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                // Results v-buffer (storage, read_write)
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: false },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        });

        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("dispatch_kernel_bg"),
            layout: &bind_group_layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: audio_vbuffer.gpu_buffer().as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: results_vbuffer.gpu_buffer().as_entire_binding(),
                },
            ],
        });

        Ok(bind_group)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_audio_frame_default() {
        let frame = AudioFrameVBuffer::default();
        assert_eq!(frame.sample_fl, 0.0);
        assert_eq!(frame.sample_fr, 0.0);
        assert_eq!(frame.sample_rl, 0.0);
        assert_eq!(frame.sample_rr, 0.0);
        assert_eq!(frame.timestamp_us, 0);
        assert_eq!(frame.frame_index, 0);
    }

    #[test]
    fn test_audio_frame_size() {
        // Verify alignment: should be 32 bytes
        assert_eq!(std::mem::size_of::<AudioFrameVBuffer>(), 32);
    }

    #[test]
    fn test_dispatch_result_default() {
        let result = DispatchResultVBuffer::default();
        assert_eq!(result.detected_frequency_hz, 0.0);
        assert_eq!(result.anomaly_score_db, 0.0);
        assert_eq!(result.confidence, 0.0);
    }

    #[test]
    fn test_dispatch_result_size() {
        // Verify alignment: should be 32 bytes
        assert_eq!(std::mem::size_of::<DispatchResultVBuffer>(), 32);
    }

    #[test]
    fn test_kernel_config_default() {
        let config = DispatchKernelConfig::default();
        assert_eq!(config.vbuffer_capacity, 19_200);
        assert_eq!(config.batch_size, 32);
        assert_eq!(config.detection_threshold_db, -40.0);
    }

    #[test]
    fn test_frame_counter() {
        // Test atomic frame counter increment
        let counter = AtomicU32::new(0);
        assert_eq!(counter.fetch_add(10, Ordering::SeqCst), 0);
        assert_eq!(counter.load(Ordering::SeqCst), 10);
    }
}
